Hands On!

In [1]:
import sys
import numpy as np

Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([1.3, 2.4, 3.12, 4])

In [4]:
a[0], b[1]

(np.int64(1), np.float64(2.4))

In [5]:
a[0:]

array([1, 2, 3, 4])

In [6]:
a[0:2]

array([1, 2])

In [7]:
print(a)
a[0:3:1]

[1 2 3 4]


array([1, 2, 3])

In [8]:
ab = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ab)
ab[::4]


[ 1  2  3  4  5  6  7  8  9 10]


array([1, 5, 9])

In [9]:
c = np.array(423)
print(c)

423


In [10]:
print(type(a))
print(a.dtype)
print(b.dtype)

<class 'numpy.ndarray'>
int64
float64


Data Types

In [11]:
integer_array = np.array([1, 2, 3, 4, 5])
print(integer_array.dtype)

newArray = integer_array.astype('i')
print(newArray.dtype)


string_array = np.array(['apple', 'banana', 'cherry'])
print(string_array.dtype)

float_array = np.array([2.4, 2.12])
print(float_array.dtype)


converted_array = np.array([1, 2, 3, 4, 5], dtype='i')
print(converted_array.dtype)


mix_array = np.array(['a', '1', '3'], dtype='S')
print(mix_array.dtype)


int_array = np.array([1, 0, 3])
new_boo_array = int_array.astype(bool)
print(new_boo_array)
print(new_boo_array.dtype)

int64
int32
<U6
float64
int32
|S1
[ True False  True]
bool


Copy vs View

In [12]:
array1 = np.array([1, 3, 4, 6, 3])
array2 = array1.copy()

array2[0] = 12

print(array1)
print(array2)

[1 3 4 6 3]
[12  3  4  6  3]


In [13]:
array1 = np.array([1, 3, 4, 6, 3])
array2 = array1.view()

array2[0] = 12

print(array1)
print(array2)

[12  3  4  6  3]
[12  3  4  6  3]


In [14]:
array1 = np.array([1, 3, 4, 6, 3])
array2 = array1.view()
array3 = array1.copy()


print(array2.base)
print(array3.base)

[1 3 4 6 3]
None


Get the Shape of an Array

In [15]:
shape_array1 = np.array([[1, 3, 5, 2], [3, 5, 6, 2]])
print(shape_array1.shape)

(2, 4)


In [16]:
shape_array2 = np.array([1, 3, 5, 2], ndmin=4)
print(shape_array2)
shape_array2.shape

[[[[1 3 5 2]]]]


(1, 1, 1, 4)

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [22]:
arr = np.array([[1,2,3],[4,3,2]])
for x in arr:
    print(x)

[1 2 3]
[4 3 2]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z) 

1
2
3
4
5
6
7
8
9
10
11
12


In [29]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x) 

1
2
3
4
5
6
7
8


In [30]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x) 

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [31]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x) 

1
3
5
7


In [32]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0,) 1
(1,) 2
(2,) 3


In [33]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [34]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [35]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr) 

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]


In [37]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [39]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [41]:
print(arr.shape)

(1, 3, 2)


In [49]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 5.5)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)
print(newarr) 

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2]) 

[1 2]
[3 4]
[5 6]


In [56]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr) 
print(newarr.count)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
<built-in method count of list object at 0x00000242C74AC400>


In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [58]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [59]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x) 

(array([0, 2, 4, 6]),)


In [63]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [64]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x) 

2


In [65]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]


In [66]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]


In [67]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [70]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [72]:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [73]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [74]:
arr = np.array([41, 42, 43, 44])

#Create an empty list
filter_arr = []

#go through each element in arr

for element in arr:
    # if the element is higher than 42, set the value to True, otherwise False: 
    if element>42:
     filter_arr.append(True)
    
    else :
      filter_arr.append(False)
      
newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False, False, True, True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)



[False, True, False, True, False, True, False]
[2 4 6]


In [76]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr >= 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True  True  True]
[42 43 44]


In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True False  True False]
[2 4 6]


In [118]:
x = np.random.randint(100)

print(x) 

53


In [119]:
x= np.random.rand()
print(x)

0.4075824309363718


In [127]:
x=np.random.randint(100, size=(5))

print(x) 

[34 93 20 31 24]


In [133]:
x=np.random.randint(100, size=(5, 2))

print(x) 

[[66 65]
 [36 21]
 [91 83]
 [26  3]
 [14 45]]


In [ ]:
x=np.random.rand(5)

print(x) 

2


In [137]:
x=np.random.rand(5,2)

print(x)

[[0.00226774 0.26148999]
 [0.73354363 0.41133824]
 [0.28792867 0.43242741]
 [0.93083023 0.04282955]
 [0.81217329 0.09945277]]


In [152]:
x=np.random.choice([3, 5, 7, 9])

print(x)

5


In [153]:
x=np.random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[7 5 3 3 7]
 [5 3 7 5 5]
 [3 7 3 7 3]]


In [177]:

x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 5 7 7 5 7 7 7 7 7 5 3 7 5 7 7 7 5 5 7 7 5 7 3 7 5 5 7 7 7 3 5 7 7 5 7 7
 7 7 7 5 7 7 5 3 7 3 7 7 7 5 7 7 7 5 5 3 3 3 7 7 7 7 7 7 3 5 5 5 3 7 3 5 5
 5 7 7 7 7 7 7 7 7 7 7 5 7 5 5 7 7 7 3 5 7 7 7 7 7 7]


In [178]:
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 3 7 5]
 [5 3 7 7 5]
 [5 5 5 3 5]]
