Hands On!

In [3]:
import sys
import numpy as np

Basic Numpy Arrays

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([1.3, 2.4, 3.12, 4])

In [6]:
a[0], b[1]

(np.int64(1), np.float64(2.4))

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[0:2]

array([1, 2])

In [20]:
print(a)
a[0:3:1]

[1 2 3 4]


array([1, 2, 3])

In [32]:
ab = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ab)
ab[::4]


[ 1  2  3  4  5  6  7  8  9 10]


array([1, 5, 9])

In [10]:
c = np.array(423)
print(c)

423


In [11]:
print(type(a))
print(a.dtype)
print(b.dtype)

<class 'numpy.ndarray'>
int64
float64


Data Types

In [55]:
integer_array = np.array([1, 2, 3, 4, 5])
print(integer_array.dtype)

string_array = np.array(['apple', 'banana', 'cherry'])
print(string_array.dtype)

float_array = np.array([2.4, 2.12])
print(float_array.dtype)


converted_array = np.array([1, 2, 3, 4, 5], dtype='i')
print(converted_array.dtype)


mix_array = np.array(['a', '1', '3'], dtype='S')
print(mix_array.dtype)

int64
<U6
float64
int32
|S1
